package types

var (
	ICAMsgs = []string{
		"/cosmos.authz.v1beta1.MsgExec",
		"/cosmos.authz.v1beta1.MsgGrant",
		"/cosmos.authz.v1beta1.MsgRevoke",
		"/cosmos.bank.v1beta1.MsgSend",
		"/cosmos.bank.v1beta1.MsgMultiSend",
		"/cosmos.distribution.v1beta1.MsgSetWithdrawAddress",
		"/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission",
		"/cosmos.distribution.v1beta1.MsgFundCommunityPool",
		"/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
		"/cosmos.feegrant.v1beta1.MsgGrantAllowance",
		"/cosmos.feegrant.v1beta1.MsgRevokeAllowance",
		"/cosmos.gov.v1beta1.MsgVoteWeighted",
		"/cosmos.gov.v1beta1.MsgSubmitProposal",
		"/cosmos.gov.v1beta1.MsgDeposit",
		"/cosmos.gov.v1beta1.MsgVote",
		"/cosmos.gov.v1.MsgVoteWeighted",
		"/cosmos.gov.v1.MsgSubmitProposal",
		"/cosmos.gov.v1.MsgDeposit",
		"/cosmos.gov.v1.MsgVote",
		"/cosmos.staking.v1beta1.MsgEditValidator",
		"/cosmos.staking.v1beta1.MsgDelegate",
		"/cosmos.staking.v1beta1.MsgUndelegate",
		"/cosmos.staking.v1beta1.MsgBeginRedelegate",
		"/cosmos.staking.v1beta1.MsgCreateValidator",
		"/cosmos.vesting.v1beta1.MsgCreateVestingAccount",
		"/ibc.applications.transfer.v1.MsgTransfer",

		"/furymod.nft.MsgIssueDenom",
		"/furymod.nft.MsgTransferDenom",
		"/furymod.nft.MsgMintNFT",
		"/furymod.nft.MsgEditNFT",
		"/furymod.nft.MsgTransferNFT",
		"/furymod.nft.MsgBurnNFT",

		"/furymod.mt.MsgIssueDenom",
		"/furymod.mt.MsgTransferDenom",
		"/furymod.mt.MsgMintMT",
		"/furymod.mt.MsgEditMT",
		"/furymod.mt.MsgTransferMT",
		"/furymod.mt.MsgBurnMT",
	}
)
